# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59b75a075545a270fe5214bf982736ecd21f703a71451e4a08e3da9b689e94410043559bacbd3b686613a80da58326ce19f422560e6618d59e5612e301fe5469

test:
  secret_key_base: 1a42afb2250c548965f0c067a36695afe798b49d2176eac3ef559a7cf699c0b03fccff791dea97f5a6246b0f8255f8cd684d36fad8f778179ff42a8f4ff0fa19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
